### ISSUE TITLE
Unable to use version 0.0.9

### ISSUE THREAD

**Issue by curia-damiano** [microsoft/ApplicationInsights-node.js-native-metrics#50]
I am using this npm in this docker file: https://github.com/curia-damiano/docker-ghost-ai/blob/master/5/alpine/ai/DOCKERFILE

If I use version 0.0.7 or 0.0.8, I am able to build it.

If I use version 0.0.9, I get this error:

#4 11.94 npm ERR! code 1
#4 11.94 npm ERR! path /opt/ai/node_modules/applicationinsights-native-metrics
#4 11.94 npm ERR! command failed
#4 11.94 npm ERR! command sh -c -- node-pre-gyp install --fallback-to-build
#4 11.94 npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/ai/node_modules/applicationinsights-native-metrics/build/Release/native_metrics.node --module_name=native_metrics --module_path=/opt/ai/node_modules/applicationinsights-native-metrics/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
#4 11.94 npm ERR! node-pre-gyp info it worked if it ends with ok
#4 11.94 npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
#4 11.94 npm ERR! node-pre-gyp info using node@16.19.1 | linux | x64
#4 11.95 npm ERR! node-pre-gyp info check checked for "/opt/ai/node_modules/applicationinsights-native-metrics/build/Release/native_metrics.node" (not found)
#4 11.95 npm ERR! node-pre-gyp http GET https://github.com/Microsoft/ApplicationInsights-node.js-native-metrics/releases/download/v0.0.9/native_metrics-v0.0.9-node-v93-linux-x64-musl.tar.gz
#4 11.95 npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Microsoft/ApplicationInsights-node.js-native-metrics/releases/download/v0.0.9/native_metrics-v0.0.9-node-v93-linux-x64-musl.tar.gz
#4 11.95 npm ERR! node-pre-gyp WARN Pre-built binaries not installable for applicationinsights-native-metrics@0.0.9 and node@16.19.1 (node-v93 ABI, musl) (falling back to source compile with node-gyp)
#4 11.95 npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Microsoft/ApplicationInsights-node.js-native-metrics/releases/download/v0.0.9/native_metrics-v0.0.9-node-v93-linux-x64-musl.tar.gz
#4 11.95 npm ERR! gyp info it worked if it ends with ok
#4 11.95 npm ERR! gyp info using node-gyp@9.1.0
#4 11.95 npm ERR! gyp info using node@16.19.1 | linux | x64
#4 11.95 npm ERR! gyp info ok
#4 11.95 npm ERR! gyp info it worked if it ends with ok
#4 11.95 npm ERR! gyp info using node-gyp@9.1.0
#4 11.95 npm ERR! gyp info using node@16.19.1 | linux | x64
#4 11.95 npm ERR! gyp ERR! find Python
#4 11.95 npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
#4 11.95 npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
#4 11.95 npm ERR! gyp ERR! find Python checking if "python3" can be used
#4 11.95 npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
#4 11.95 npm ERR! gyp ERR! find Python checking if "python" can be used
#4 11.95 npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
#4 11.95 npm ERR! gyp ERR! find Python
#4 11.95 npm ERR! gyp ERR! find Python **********************************************************
#4 11.95 npm ERR! gyp ERR! find Python You need to install the latest version of Python.
#4 11.95 npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#4 11.95 npm ERR! gyp ERR! find Python you can try one of the following options:
#4 11.95 npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#4 11.95 npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
#4 11.95 npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
#4 11.95 npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
#4 11.95 npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#4 11.95 npm ERR! gyp ERR! find Python For more information consult the documentation at:
#4 11.95 npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#4 11.95 npm ERR! gyp ERR! find Python **********************************************************
#4 11.95 npm ERR! gyp ERR! find Python
#4 11.95 npm ERR! gyp ERR! configure error
#4 11.95 npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
#4 11.95 npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
#4 11.95 npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
#4 11.95 npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
#4 11.95 npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
#4 11.95 npm ERR! gyp ERR! stack     at exithandler (node:child_process:410:5)
#4 11.95 npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:422:5)
#4 11.95 npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
#4 11.95 npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
#4 11.95 npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:485:16)
#4 11.95 npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
#4 11.95 npm ERR! gyp ERR! System Linux 5.15.90.1-microsoft-standard-WSL2
#4 11.95 npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/opt/ai/node_modules/applicationinsights-native-metrics/build/Release/native_metrics.node" "--module_name=native_metrics" "--module_path=/opt/ai/node_modules/applicationinsights-native-metrics/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
#4 11.95 npm ERR! gyp ERR! cwd /opt/ai/node_modules/applicationinsights-native-metrics
#4 11.95 npm ERR! gyp ERR! node -v v16.19.1
#4 11.95 npm ERR! gyp ERR! node-gyp -v v9.1.0
#4 11.95 npm ERR! gyp ERR! not ok
#4 11.95 npm ERR! node-pre-gyp ERR! build error
#4 11.95 npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/ai/node_modules/applicationinsights-native-metrics/build/Release/native_metrics.node --module_name=native_metrics --module_path=/opt/ai/node_modules/applicationinsights-native-metrics/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
#4 11.95 npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/ai/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
#4 11.95 npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
#4 11.95 npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1100:16)
#4 11.95 npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
#4 11.95 npm ERR! node-pre-gyp ERR! System Linux 5.15.90.1-microsoft-standard-WSL2
#4 11.95 npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/opt/ai/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
#4 11.95 npm ERR! node-pre-gyp ERR! cwd /opt/ai/node_modules/applicationinsights-native-metrics
#4 11.95 npm ERR! node-pre-gyp ERR! node -v v16.19.1
#4 11.95 npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10
#4 11.95 npm ERR! node-pre-gyp ERR! not ok
#4 11.95
#4 11.95 npm ERR! A complete log of this run can be found in:
#4 11.95 npm ERR!     /root/.npm/_logs/2023-03-08T16_52_35_607Z-debug-0.log
------
executor failed running [/bin/sh -c mkdir /opt/ai &&         cd /opt/ai &&         npm init -y &&         npm install --production --save applicationinsights@^2.5.0 &&         npm install --production --save applicationinsights-native-metrics@^0.0.9]: exit code: 1
damiano@CURIADAMIANOPC:~/docker-ghost-ai$

This problem seems to be similar to the existing issue #9 .

**Comment by hectorhdzg** [comment]
@curia-damiano please use version 0.0.8 for now, we are aware of this issue, apparently there are some security concerns about generating the musl binaries for Alpine Linux.

**Comment by curia-damiano** [comment]
Thank you Hector! It would be nice if you could update & close this issue once you will fix version 0.0.9.

**Comment by curia-damiano** [comment]
Hi @hectorhdzg , I see new version 0.10.0.
Does it solve this issue, of deployment on Alpine Linux?

And in any case, have you also updated 0.9.0 to solve this issue?

**Comment by sidx64** [comment]
Adding this here since this is still an open issue.

Facing the same problem installing applicationinsights-native-metrics v0.10.0:

Node version: 18.18.2
NPM version: 9.8.1

`
npm install --save applicationinsights-native-metrics
npm ERR! code 1
npm ERR! path /workspaces/TimeTracker-cap/timetracker-api/node_modules/applicationinsights-native-metrics
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/workspaces/TimeTracker-cap/timetracker-api/node_modules/applicationinsights-native-metrics/build/Release/native_metrics.node --module_name=native_metrics --module_path=/workspaces/TimeTracker-cap/timetracker-api/node_modules/applicationinsights-native-metrics/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.11
npm ERR! node-pre-gyp info using node@18.18.2 | linux | arm64
npm ERR! node-pre-gyp info check checked for "/workspaces/TimeTracker-cap/timetracker-api/node_modules/applicationinsights-native-metrics/build/Release/native_metrics.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/Microsoft/ApplicationInsights-node.js-native-metrics/releases/download/v0.0.10/native_metrics-v0.0.10-node-v108-linux-arm64-glibc.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Microsoft/ApplicationInsights-node.js-native-metrics/releases/download/v0.0.10/native_metrics-v0.0.10-node-v108-linux-arm64-glibc.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for applicationinsights-native-metrics@0.0.10 and node@18.18.2 (node-v108 ABI, glibc) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Microsoft/ApplicationInsights-node.js-native-metrics/releases/download/v0.0.10/native_metrics-v0.0.10-node-v108-linux-arm64-glibc.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@18.18.2 | linux | arm64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@18.18.2 | linux | arm64
npm ERR! gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v18.18.2/node-v18.18.2-headers.tar.gz
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v18.18.2/node-v18.18.2-headers.tar.gz failed, reason: Client network socket disconnected before secure TLS connection was established
npm ERR! gyp ERR! stack     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
npm ERR! gyp ERR! stack     at ClientRequest.emit (node:events:517:28)
npm ERR! gyp ERR! stack     at TLSSocket.socketErrorListener (node:_http_client:501:9)
npm ERR! gyp ERR! stack     at TLSSocket.emit (node:events:529:35)
npm ERR! gyp ERR! stack     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR! gyp ERR! stack     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR! gyp ERR! System Linux 6.5.11-linuxkit
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/workspaces/TimeTracker-cap/timetracker-api/node_modules/applicationinsights-native-metrics/build/Release/native_metrics.node" "--module_name=native_metrics" "--module_path=/workspaces/TimeTracker-cap/timetracker-api/node_modules/applicationinsights-native-metrics/build/Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
npm ERR! gyp ERR! cwd /workspaces/TimeTracker-cap/timetracker-api/node_modules/applicationinsights-native-metrics
npm ERR! gyp ERR! node -v v18.18.2
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/workspaces/TimeTracker-cap/timetracker-api/node_modules/applicationinsights-native-metrics/build/Release/native_metrics.node --module_name=native_metrics --module_path=/workspaces/TimeTracker-cap/timetracker-api/node_modules/applicationinsights-native-metrics/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/workspaces/TimeTracker-cap/timetracker-api/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:303:5)
npm ERR! node-pre-gyp ERR! System Linux 6.5.11-linuxkit
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/workspaces/TimeTracker-cap/timetracker-api/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /workspaces/TimeTracker-cap/timetracker-api/node_modules/applicationinsights-native-metrics
npm ERR! node-pre-gyp ERR! node -v v18.18.2
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.11
npm ERR! node-pre-gyp ERR! not ok
`

**Comment by curia-damiano** [comment]
I kindly ask if we can find a solution about how to use Application Insights in NodeJS applications with Linux Alpine distributions

**Comment by sidx64** [comment]
**https://github.com/microsoft/ApplicationInsights-node.js-native-metrics/issues/50#issuecomment-1884352135**

Please ignore this issue. I encountered this because of newly applied corporate firewalls blocking some cert validations.

**Comment by curia-damiano** [comment]
Ok thanks for the feedback.
Still I am awaiting for issue resolution for my use case.

**Comment by curia-damiano** [comment]
Hey @hectorhdzg , does version 0.0.10 fix this issue?

**Comment by curia-damiano** [comment]
I close this case because luckily I have found how to use this library in an alpine distribution without errors
